name: the_movies_expore
description: "Flutter app for exploring movies"
publish_to: 'none'

version: 0.0.1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.3+1
  flutter_bloc: ^8.1.5
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  go_router: ^14.1.3
  google_fonts: ^6.2.1
  injectable: ^2.4.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.3.0
  retrofit: ^4.1.0
  flutter_localizations:
    sdk: flutter
  flutter_sticky_header: ^0.6.5
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  shared_preferences: ^2.2.3
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  shimmer: ^3.0.0
  share_plus: ^9.0.0
  animated_read_more_text: ^0.0.6
  flutter_cache_manager: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  injectable_generator: ^2.6.1
  build_runner: ^2.4.10
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.0

flutter:
  generate: true 
  uses-material-design: true

  assets:
    - assets/google_fonts/
    - assets/image/
